version: "3.9"

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm_gateway
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    command: [ "--config", "/app/config.yaml", "--port", "4000" ]
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:15
    container_name: litellm_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  # agent_git:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.agent
  #   container_name: agent_git
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
  #     - LITELLM_BASE_URL=http://litellm:4000/v1
  #     - MODEL_NAME=${MODEL_NAME:-gemini-1.5-pro}
  #     - GIT_ORG=${GIT_ORG:-Qoin-Digital-Indonesia}
  #     - GITHUB_TOKEN=${GITHUB_TOKEN:-}
  #   volumes:
  #     - ./data:/app/data
  #     - ./tools:/app/tools
  #   depends_on:
  #     - litellm
  #   restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: litellm_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  ollama_pull_model:
    image: curlimages/curl:latest
    container_name: litellm_ollama_pull
    command: >
      sh -c "echo 'Menunggu Ollama siap...' && sleep 10 && curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"qwen2.5-coder:14b\"}' && echo '\nSelesai!'"
    depends_on:
      - ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: litellm_open_webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui_data:/app/backend/data
    depends_on:
      - ollama
    restart: always

volumes:
  postgres_data:
  ollama_data:
  open-webui_data:
