apiVersion: v1
kind: Service
metadata:
  name: litellm-service
  labels:
    app: litellm
spec:
  selector:
    app: litellm
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 4000        # ClusterIP port (internal)
      targetPort: 4000  # container port
      nodePort: 8888    # akses eksternal: http://<node-ip>:8888
